### PR TITLE
Fix generated enum field code without defaults.

### PR DESCRIPTION
**Pull request by matttproud**
The original generated Go code for Thrift enum fields possessed an
anomaly whereby structs that have enum fields without default values
assumed such a field is unset if its value is zero.  Now, according to
http://wiki.apache.org/thrift/Tutorial, an enum with unvalued elements
starts its first element at zero, so the original means of field
comprehension has problems, specifically because Go default
initialization value for numbers is zero.

To remedy this, the code generator now assumes internally that enums
are int64 instead of the original int (i.e., int32); however, all
consumers of the enum still see the enum as int.  With that, structs
with enum fields that lack assigned value now default to
math.MinInt32 - 1 and use this to validate whether the field was
explicitly set.

### CODE REVIEW

**Comment by pomack** [comment]
Hey Matt,

Looks like you've added some commits to this merge.  Should I take a look at this now or is it still incomplete?

**Comment by matttproud** [comment]
Ahh.  I should be done with this soon.  I added some end-to-end tests against a Java based verification suite and uncovered some additional errors—unrelated to my underlying changes but critical to fix for proper operation of this change.  :-)  I'll let you know when I'm ready.

**Comment by matttproud** [comment]
Hey Aalok,

This should be ready to review now.  Thank you for your patience.

After this is submitted, I am planning on doing two things:
1. Adding an optional test suite that validates end-to-end communication with the cross of a {go,java} {client,server}.
2. Passing the generator code through `astyle` to to cleanup some irregularities.  Any thoughts on the desired format for this?

Matt

**Comment by pomack** [comment]
I'm not familiar with `astyle`, so I'll leave that decision to you.

**Pull request merged**
