### PR TITLE
Please review my optimizations and code generation fixes

### PR DESCRIPTION
**Pull request by apesternikov**
library:
- thrift's BYTE type is signed (so it is int8, not byte)
- asynchronous protocol is removed as irrelevant in go
  code generation:
- safer constants using typed vars
- int64 consts over 2^32 dont blow up
- negative byte consts
- generated struct doesn't include type metainformation field to avoid metainfo creating for every instance
- map, list, set initializers didn't work
  tests:
- use generated Work and CalculateArgs

### CODE REVIEW

**Comment by pomack** [comment]
Wow, thanks Aleksey! I don't have time to look through this for the next couple of weeks and I definitely want to take a good look to understand all the changes. I'll try to find some time at the beginning of March.

**Comment by apesternikov** [comment]
sure. I hope I will have my other planned things done by that time. (I started short summary here https://github.com/apesternikov/thrift4go/wiki/Roadmap)

**Comment by sdming** [comment]
it's cool, I tried apesternikov/thrift4go, but i got error when generate code for Hbase thrift api, it stoped at code:
type TRowResult struct {
  Row Text "row"; // 1

**Comment by sdming** [comment]
bug of TlLIst, it break when i=0

if len(p.l) >= i {
  p.l[i] = data
} else {
 p.l = append(p.l, data)
}

**Comment by apesternikov** [comment]
sdming,
compiler is fixed, it would be great if you try and tell us how it works.

**Comment by sdming** [comment]
still can not compile Hbase thrift interface

error happen at the logic to handle key of map 

you can download hbase thrift interface from http://wiki.apache.org/hadoop/Hbase/ThriftApi

**Comment by sdming** [comment]
type Text []byte

you make a map map[string]XXX

but you set value with
map[Text] = xxx

**Comment by apesternikov** [comment]
sorry, I forgot to commit my last changes. please test

**Comment by sdming** [comment]
still many errors

an example

type TRegionInfo struct {
    ...
    Version    int8  "version"    // 5
    ...
}

func (p *TRegionInfo) readField5(iprot thrift.TProtocol) {
    ...
    v30, err31 := iprot.ReadByte()  
    p.Version = v30
    ...
}

...
cannot use v30 (type byte) as type int8 in assignment
...

**Comment by apesternikov** [comment]
sdming, please make sure that your library is up to date. please update it with
go get -u github.com/apesternikov/thrift4go/lib/go/src/thrift

ReadByte() returns int8:
https://github.com/apesternikov/thrift4go/blob/master/lib/go/src/thrift/tprotocol.go#L65

and this is one of the changes from the original library:
https://github.com/pomack/thrift4go/blob/master/lib/go/src/thrift/tprotocol.go#L65

**Comment by sdming** [comment]
it's strange, go get -u does not work, but git clone works fine

**Pull request closed without merging**
